services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://finance-api.endabelyu.com
    container_name: mili-web
    ports:
      - "4016:4016"
    restart: unless-stopped